### ISSUE TITLE
content/post/2023-09-19-tracing-is-better

### ISSUE THREAD

**Issue by ghost** [Pondidum/pondidum.github.io#11]
this post mentions some `tracing` module repeatedly, but never links to it. looks like this is it:

https://github.com/Pondidum/Trace

**Comment by Pondidum** [comment]
I can only find a mention of CI tracing and a link the blog post about it - no other mentions of `trace` or anything related that I can see - can you show me where you mean?

**Comment by ghost** [comment]
1. go here https://andydote.co.uk/2023/09/19/tracing-is-better/
2. Ctrl+F
3. `tracing.`

**Comment by Pondidum** [comment]
Tracing is a concept, provided in this case by OpenTelemetry.  I have a tool which emits traces, called `trace`.  Nothing in this article refers to my tool.

Edit: OTEL definitions docs: https://opentelemetry.io/docs/concepts/signals/traces/

**Comment by ghost** [comment]
can you please link to the `tracing` module? sorry if I am not being clear, but I think I have been extremely clear. here is an example code block from the article:

~~~go
if err := MarkReadyForUsage(ctx, container, templateIds); err != nil {
- return nil, err
+ return nil, tracing.Error(span, err)
}
~~~

where is the `tracing` module hosted?

**Comment by Pondidum** [comment]
Ah, now I understand your confusion!

The `tracing` package is not hosted anywhere.  Its just a package I tend to create in golang programs to hold all my tracing utility methods.

One of the methods is actually written into the blogpost too:

```go
func Error(s trace.Span, err error) error {
  s.RecordError(err)
  s.SetStatus(codes.Error, err.Error())

  return err
}
```

For example, `tracing.StringSlice` looks like this:

```go
func StringSlice(s Span, key string, slice []string) {
    s.SetAttributes(attribute.StringSlice(key, slice))
}
```

**Comment by ghost** [comment]
OK, can you please upload the module somewhere?

**Comment by Pondidum** [comment]
No.  They are a few liner helper functions -  its something you should create yourself to suit your use cases or style.

**Comment by ghost** [comment]
OK suit yourself, but making a blog post, wherein you post snippets of a closed source Go module, is highly confusing. people reading the post are possibly going to want to run that code, and they aren't going to be able to, because the code is closed source, and thats not been made clear in the post that I can tell.

It would be helpful if a note was added to the blog post that `tracing` is closed source.

**Comment by Pondidum** [comment]
The blog is full of example code it's not supposed to run
